version: '3'
services:
  redis:
    image: redis
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c "python web/manage.py migrate && python web/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db
      - redis
      - mongodb
